# Generated by Django 4.2.7 on 2023-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(default=None, null=True, upload_to='post_images/', verbose_name='Главное изображение'),
        ),
    ]
