# Generated by Django 4.2.7 on 2023-11-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='img', verbose_name='Главное изображение'),
        ),
    ]
